### ISSUE TITLE
lets go site not shown

### ISSUE THREAD

**Issue by jo-ei** [werdeil/pibooth#103]
**Describe the bug**
If there is the possibility to choose between a different number of images, a "Lets Go" message will appear. If you don't have the choice because 1 picture is fixed, it doesn't come.

**Steps to reproduce the bug**
set config to 
`captures = (1, 4)`

change config to
`captures = (1)`

**Environment**
 - Pibooth version: 1.2.0

**Comment by anxuae** [comment]
Hi @jo-ei,

This is not a bug but a feature. If you have not choice, there is no message displayed.

anxuae

**Comment by jo-ei** [comment]
hi @anxuae ,
you can show me the place in the code where I could add it so that it is shown without selection (for 1 photo)

Thanks
