### ISSUE TITLE
adjustable resolution of the finished image

### ISSUE THREAD

**Issue by jo-ei** [werdeil/pibooth#107]
**Is your feature request related to a problem? Please describe.**
Hi,
at the moment it looks like the final image is configured with a fixed resolution of 3600 x 2400 (or  2400 x 3600)

**Describe the solution you'd like**
config option for final picture size

**Comment by werdeil** [comment]
Can you be more specific do you want other resolution with the same 3/2 ratio or a new ratio?

**Comment by jo-ei** [comment]
hi,
i think either the resolution of the monitor is enough to display it fullscreen (#104) or the resolution of the printer (300dpi).

retained 3/2 resolution ?? -> I think yes

or is there an option to configure the used template (with final size, picture size, picture poition, text position, ...)  to create picture process?

**Comment by anxuae** [comment]
A solution could be to add a new hook in the plugin system called when the finale picture is created. It will permit to post process the finale picture by changing attributes of the `PictureMaker` or replacing the default one by a  custom `PictureMaker` .

**Comment by anxuae** [comment]
Implemented in PR #134

**Comment by werdeil** [comment]
As said by @anxuae, since PR #134 you can define your own `PictureFactory` as a pibooth plugin and use the corresponding hooks to do your own template.

I may try to do one as an example soon but in the meantime I'm closing the issue.
