### ISSUE TITLE
Image deletion (enhancement)

### ISSUE THREAD

**Issue by sblanc27** [werdeil/pibooth#108]
Dear Team,

A new functionality which would be really appreciated is to give the end-user the choice to delete the photo taken for any reason (quality, face, ...), of course a switch on the configuration would be appreciated to activate/deactivate the feature.

A possible implementation of it could be an additional screen between the state "Processing" and "Print".
![layout_deletion](https://user-images.githubusercontent.com/48512672/72255375-dafdef00-3606-11ea-9204-e9d12b5dc5f6.JPG)

**Comment by werdeil** [comment]
I don't like adding new interstitial screens, as it increase the workflow time (if the user want to keep the photo).

An option I could think of is to use the second button on the print page, we would have something like "<- please forget this ugly photo" "Print the photo ->"

But this won't address the usage without printing.

@anxae what do you think?

**Comment by anxuae** [comment]
I agree with you @werdeil, a new arrow can be added below the picture to print in order to "forget" the picture

**Comment by anxuae** [comment]
@werdeil should we make the "print" state always displayed since it is used to propose the image deletion?
(Currently the state is skipped if no printer installed)

**Comment by werdeil** [comment]
For me not as it is now, if we make it always displayed we shall change the complete layout (including arrows) depending on the fact that there is print or not.

I see the forgot feature most as a way to avoid waiting time on the print screen, if there is no print option user doesn't wait so no need to add an action here...

**Comment by anxuae** [comment]
That's ok for me.

Other point: the folders in `raw` should not be also moved in a raw folder inside the `forget` one?

**Comment by werdeil** [comment]
I would say no too, for me all the raws shall be kept in the same folder.

**Comment by anxuae** [comment]
But a least a folder `forget` in the `raw` one, be cause if I want to upload in google drive all the raw photo, I need to select manually which one is forgotten or not...

**Comment by werdeil** [comment]
I disagree on that, for me raws shall be kept as they are.

There can be good raw images from a forgotten final picture, I don't think we shall put them away.
