### ISSUE TITLE
Pi Zero or Pi 1. Generation

### ISSUE THREAD

**Issue by pedakas** [werdeil/pibooth#110]
Hello, 
I have a short question, will it work on a RPI Zero or a RPI 1. Generation?

Thanks!

**Comment by werdeil** [comment]
Technically it should work, but it will be too slow to be useable I think.

We didn't test on our side with a RPi zero nor Roi 1 but when we tested on a RPi 2 it was too slow. That's why we tell "1 Raspberry Pi 3 Model B (or higher)" in the README.

**Comment by pedakas** [comment]
Thank you very much!

**Comment by mattdsteele** [comment]
Hi folks, I have a similar, but opposite question. Has anyone tested on the Raspberry Pi 4? Any idea whether you would see significant performance improvements?

Since my current hardware (Pi Zero) won't cut it, I'm wondering if it's worth spending a little more buying the latest 4 model.

**Comment by werdeil** [comment]
Hi @mattdsteele Sorry for the late answer as the issue is closed we didn't see your question.

I would say the bigger the better, appart from the global speed, the main slowness we get on old Raspberry Pi is processing part (where we merge the capture in one picture), the last Raspberry Pi will be better on this part.

**Comment by mattdsteele** [comment]
No worries, I ended up picking up a 4 in the interim, and it's been working well!

**Comment by jeyremy** [comment]
@mattdsteele May i ask what version of the 4 are you using ? 
i'm about to buy one... but i dont know if 2gb will be enought or go to the 4gb version...

**Comment by mattdsteele** [comment]
@jeyremy I used the 2gb version, and it seemed to work fine!
