### ISSUE TITLE
More of a question.

### ISSUE THREAD

**Issue by DaddioD** [werdeil/pibooth#112]
How did you get your landscape final to have that small of margins. All my attempts seem to make the picture smaller.

![pibooth_landscape](https://user-images.githubusercontent.com/53852613/73405559-d51c3500-42b9-11ea-82db-5629ec36dbf3.jpg)

**Comment by werdeil** [comment]
Hi DaddioD,

I think that you are looking for the "capture_cropping" setting, which is by default set to false. Have you tried with this setting set to True?

You can either change it from the file in the .config folder or via the settings menu, in the picture submenu, item "Crop captures".

Tell us if it answers your question.

**Comment by DaddioD** [comment]
Sorry to respond late. Will be able to try that tomorrow.

**Comment by anxuae** [comment]
Hi @DaddioD , 

Have you try the solution proposed by @werdeil ?

**Comment by anxuae** [comment]
I close this issue, because I have no news.
Please reopen it if issue is persisting.
