### ISSUE TITLE
Introduce a plugin system

### ISSUE THREAD

**Issue by werdeil** [werdeil/pibooth#115]
Introduce a plugin system (eg https://pypi.org/project/pluggy ) to let the possibility to integrate custom functions at specific steps of the pibooth process.

It will allow the integration of dedicated behavior outside of the main pibooth code, for example create a plugin to:
- Publish picture at the print step #52
- Neopixel support at multiple steps #100 
- Extract printing out of pibooth as it is not a mandatory step
- Execute external commands #117
...

This is a big feature, setting a milestone for pibooth 2.0

**Comment by anxuae** [comment]
First implementation in https://github.com/werdeil/pibooth/tree/dev-pluggy

**Comment by anxuae** [comment]
PR under review https://github.com/werdeil/pibooth/pull/124
