### ISSUE TITLE
photo rotation

### ISSUE THREAD

**Issue by oksimple** [werdeil/pibooth#116]
Hi friend, your project is awesome, but I think if you can rotate the photo, it will be more widely used.

![$8%%7 P@%J@KMGD{6XK3AO4](https://user-images.githubusercontent.com/10106142/75664385-5c8c0800-5cad-11ea-9ae7-bfd4bd5cdc70.png)

**Comment by anxuae** [comment]
This proposal is interesting, however it is far to the current implementation of the ``pibooth`` software.
It require lots of picture handling thanks to PIL or OpenCv libs, and i think, the orientation of each picture need to be defined in the configuration, which may be tricky for the newbie.

**Comment by oksimple** [comment]
@anxuae I think it can be saved to the situation of the template. Select a template before taking a picture and replace the placeholder picture in the template after taking a picture. This is not complicated for novices and can make the template widely shared.

**Comment by anxuae** [comment]
A solution could be to add a new hook in the plugin system called when the finale picture is created. It will permit to post process the finale picture by changing attributes of the `PictureMaker` or replacing the default one by a  custom `PictureMaker` .

**Comment by werdeil** [comment]
As said by @anxuae, since PR #134 you can define your own `PictureFactory` as a pibooth plugin and use the corresponding hooks to do your own template.

I may try to do one as an example soon but in the meantime I'm closing the issue.
