### ISSUE TITLE
change color text if use background image

### ISSUE THREAD

**Issue by sravel** [werdeil/pibooth#122]
Thank you for this great code which corresponds exactly to what I am looking for.

However, I have a small modification that I would like.
- My problem is that I have a mid image in the background and the majority color which is light green. but on the white background of the photos it is not visible. By looking at the code I managed to modify in the file "background.py" line 148
```self._background_color = pictures.get_pygame_main_color(self._background)```
to
```self._background_color = (0,0,0)  #tuple color```

- Another question: is it possible to not recolor the images in black and white?
see lines 71/72 of the pictures / __ init __ () file optional ?

**Describe the solution you'd like**
- One solution would be to set image and / or text color
example: if image alone, majority color
otherwise image and text color

- solution for 2
```
if color and to_black_and_white: #to_black_and_white is boolean load on config file
    pil_image = set_picto_color(pil_image, (255,255,255), (0,0,0))
```
![image](https://user-images.githubusercontent.com/11534773/76962706-001d1f80-6920-11ea-9f4e-b58d8603f2c8.png)

Thanks

Sébastien

**Comment by werdeil** [comment]
Hi thanks for the feedback

I'm not sure I understand: your issue is that the text is in light green as your background main color is in light green too?

**Comment by sravel** [comment]
yes and no, i want to change the color of text "1 photo" and "2 photos", because i use background image and your code select the main color of image background. 
if I change the code line
```self._background_color = pictures.get_pygame_main_color(self._background)```
to 
```self._background_color = (0,0,0)```
the text color change in black
it is better to have parameter in the file config for adjust color instead of change the code.

**Comment by werdeil** [comment]
> your code select the main color of image background.

Yes this is the intended behavior so the whole thing work smoothly with any background/ text color

Have you considered changing the text color? it light-green on white is not readable so is white on light-green

Here is a small test I just did with a light-green background and white or black text color.

<img width="797" alt="Capture d’écran 2020-03-18 à 15 38 33" src="https://user-images.githubusercontent.com/6229844/76972550-06ff5e80-692f-11ea-9104-6be98c37b23e.png">
<img width="798" alt="Capture d’écran 2020-03-18 à 15 39 25" src="https://user-images.githubusercontent.com/6229844/76972552-08c92200-692f-11ea-8cc2-2e02c37f004e.png">

**Comment by sravel** [comment]
Ok I understood, in fact my two points are linked.
I will try to explain my request better with examples of capture:
in the config file, I have the color of text in white
and an image in the background.
if i go back to the original code when i launch i have this rendering:
![couleurBlanc](https://user-images.githubusercontent.com/11534773/76975831-68293100-6933-11ea-839f-894e29b6aa95.png)

Now I would like to keep the image in color (the butterfly) so I comment the code on file pictures / __ init __ () line 71
```
if color:
             pil_image = set_picto_color (pil_image, color, bg_color)
```
i have this rendering:
![colorImg](https://user-images.githubusercontent.com/11534773/76976207-f6051c00-6933-11ea-833c-a7ef9dbb4dfe.png)
so now I want to change only the color of the text "1 photo" and "2 photos" to RGB color define on config file.
for the moment i change the code on file  "background.py" line 148
to ```self._background_color = (0,0,0) #tuple color```
so I have this rendering:
![final](https://user-images.githubusercontent.com/11534773/76976582-7166cd80-6934-11ea-8ed4-28dabf17518c.png)

the aim of my issue is to have somme option on config file instead of change code.
I now python so I try to modify but i don't explore all your code for the moment !!!!

Thanks
