### ISSUE TITLE
Previous capture not displayed when current is forgotten

### ISSUE THREAD

**Issue by anxuae** [werdeil/pibooth#129]
**Describe the bug**
When a picture is forgotten, the previous one is no more displayed on the "wait" state.

**Steps to reproduce the bug**
1. Run a first capture sequence
2. Run a second capture sequence
3. Forget the picture of the second sequence
4. The first capture is not displayed on the "wait" screen

**Environment**
 - Mac OSX
 - Camera embedded
 - Pibooth version 1.2.0 dev

**Comment by werdeil** [comment]
For me it is the expected behavior, not sure that displaying an old image would be understandable...

**Comment by werdeil** [comment]
What about adding a way to define a default image that will be shown at startup and when the image is forgotten?

**Comment by anxuae** [comment]
Yes this can be a possibility.

However viewing the photo of friends during a party is funny, and for me there is no ambiguity to show the last not forgotten picture.

**Comment by anxuae** [comment]
Proposal 1

![hat_mustashe](https://user-images.githubusercontent.com/25277953/77407381-58d43880-6db6-11ea-8409-571b7555441d.png)

**Comment by anxuae** [comment]
Proposal 2

![c71924c7e9aca22967ea5591d9dd0fad](https://user-images.githubusercontent.com/25277953/77410389-15c89400-6dbb-11ea-8d38-cae1182f43eb.png)

https://www.pinterest.fr/pin/791085490779175668/

**Comment by werdeil** [comment]
But I thought you wanted the previous unforgotten picture?

**Comment by anxuae** [comment]
A nice picture is also ok for me ;-)

**Comment by werdeil** [comment]
Need to handle the print option: what do you think: we gave the option to print the second previous or we show the image but not the option to print it?

**Comment by anxuae** [comment]
Maybe don't need to print, the second previous may already be printed several times.
A simple solution is set the `app.nbr_duplicates` to a high value.

**Comment by werdeil** [comment]
Added the app.nr_duplicates part too, please review :-)

**Comment by werdeil** [comment]
Solved by https://github.com/werdeil/pibooth/commit/4c2bc2a6874d19907eb3c1c6e1246fefda85317a
