### ISSUE TITLE
OSError: Neither Raspberry Pi nor GPhoto2 nor OpenCV camera detected

### ISSUE THREAD

**Issue by chulo601** [werdeil/pibooth#132]
Hi 
Im using the raspberry pi camera v2.1 but i install gphoto2 & Opencv  for the future when i get a DSLR.  im get OSError: Neither Raspberry Pi nor GPhoto2 nor OpenCV camera detected

how can i fix the error so i can work with raspberry pi camera v2.1?

thank you for any help.

**Comment by anxuae** [comment]
Hi @chulo601 

Did you configure the picamera and activate it in the RPI config like explained here : https://thepihut.com/blogs/raspberry-pi-tutorials/16021420-how-to-install-use-the-raspberry-pi-camera ?

**Comment by chulo601** [comment]
thank you for the reply.  the camera wasnt working so i got a webcam
