### ISSUE TITLE
Handle concatenation when there are not 4 pictures

### ISSUE THREAD

**Issue by werdeil** [werdeil/pibooth#15]

**Comment by anxuae** [comment]
I have done simple changes to avoid crashes (see https://github.com/werdeil/pibooth/commit/529f2b28a674423a31699710df688a108ea2aba0)

But maybe need to be optimized

**Comment by anxuae** [comment]
I think we can close it?

**Comment by werdeil** [comment]
Yes closing it  as 529f2b2 is enough
