### ISSUE TITLE
Rework code on language handling

### ISSUE THREAD

**Issue by werdeil** [werdeil/pibooth#16]
In commit 86377269e9d834118b906d7c602637371361e514 I have introduced a language option in the config, but this option is read in the __init__.py of the pictures folder.

I don't like the idea of having a part of the config hidden on the __init__.py file. We need find a better way.

**Comment by anxuae** [comment]
https://github.com/werdeil/pibooth/commit/140e307d7cb4b253c0c2af716413646f334255d7
