### ISSUE TITLE
Find a way to install the package when gphoto2 or cups is not installed

### ISSUE THREAD

**Issue by werdeil** [werdeil/pibooth#17]
As it is very long and optional to have them it shall be possible to install pibooth via pip without them.

**Comment by anxuae** [comment]
The only solution is to remove them from the`install_requires` setup. 

Raise an error if the user try to use them without installe them beforehand manually.

**Comment by werdeil** [comment]
Then for me there are two options:
- Remove them from install_requires as you describe
or
- Add the workaround in the documentation.

Which one do you prefer?

**Comment by anxuae** [comment]
the only possible workaround is `pip install pibooth --no-deps`, in that case all dependencies have to be installed manually.

**Comment by anxuae** [comment]
Ok for workaround or I remove the dependencies

**Comment by werdeil** [comment]
workaround it is

**Comment by anxuae** [comment]
https://github.com/werdeil/pibooth/commit/1ee5b8569bab82e712ff3043fac513e19d03f64d
