### ISSUE TITLE
Preview position to be centered

### ISSUE THREAD

**Issue by werdeil** [werdeil/pibooth#2]

**Comment by anxuae** [comment]
I can not reproduce this behavior on my screen.
Are you sure that your repository was up to date when your are test?

**Comment by anxuae** [comment]
Found the reason: my rpi is not able to find correct resolution for my TV => the desktop have not the full screen size, which introduce a offset in positions.

https://github.com/werdeil/pibooth/commit/8fa7211091e1db07aca10384eba50236e3ee4444
