### ISSUE TITLE
Blink status of all leds should in sync

### ISSUE THREAD

**Issue by werdeil** [werdeil/pibooth#23]
I think both instances of PtbLed shall use share info to blink in sync.

**Comment by anxuae** [comment]
Please have a try with this patch https://github.com/werdeil/pibooth/commit/abc5d4e7499208ce6b965b066198eaba30122350

**Comment by anxuae** [comment]
https://github.com/werdeil/pibooth/commit/7b83148dd176857b755d15e9b07bdadd6d96342a
