### ISSUE TITLE
Add option to keep horizontal flip for the photo

### ISSUE THREAD

**Issue by werdeil** [werdeil/pibooth#24]

**Comment by anxuae** [comment]
You means disable the Flip mode during the preview?

**Comment by werdeil** [comment]
As discussed, the option is to keep the mirror in the preview and add an option to have the photo as a mirror too.

**Comment by anxuae** [comment]
https://github.com/werdeil/pibooth/commit/8a8152e28fc38e3094bae8062a4de8e8e3274e3a
