### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by werdeil** [werdeil/pibooth#26]
Following second topic on issue #25, we need to implement a landscape mode

**Comment by thifi** [comment]
Thank you for opening this issue.
Actual the software takes 4 pictures in portrait mode and combine it to a postcard in portrait mode with footer 1 and 2 on the small side.
I wish a postcard in landscape mode with 4 pictures on it and a footer and a header on the large sides.
Another option is to use a personal template as backround like attached.

![images 1](https://user-images.githubusercontent.com/23024896/37493643-eb95ffee-28a5-11e8-9723-11d308db0c76.jpeg)
![images 2](https://user-images.githubusercontent.com/23024896/37493644-ebb198e4-28a5-11e8-9d98-f43c3d7a9a30.jpeg)
![images](https://user-images.githubusercontent.com/23024896/37493645-ebcabfc2-28a5-11e8-8ebb-a5ef8dd3a909.jpeg)

**Comment by anxuae** [comment]
Features available in release https://github.com/werdeil/pibooth/releases/tag/0.0.7
Package uploaded on Pypi

The issue on template as background is not yet addressed (open a new ticket?)

**Comment by werdeil** [comment]
Closing issue
