### ISSUE TITLE
Handle an hybrid case with preview with picamera and photo with gphoto2

### ISSUE THREAD

**Issue by werdeil** [werdeil/pibooth#28]

**Comment by anxuae** [comment]
First version available since https://github.com/werdeil/pibooth/commit/dc7bd71071756e2312d5ae7f44ec6675b935d6a8

To be tested

**Comment by werdeil** [comment]
Tested and corrected :-)  c0e4abe
We just need to adjust the hardware to have a preview showing the same image as the gphoto2 device

**Comment by anxuae** [comment]
Features available in release https://github.com/werdeil/pibooth/releases/tag/0.0.7
Package uploaded on Pypi
