### ISSUE TITLE
Glitch on start_preview()

### ISSUE THREAD

**Issue by bderenzo** [werdeil/pibooth#34]
Hi,

There is a glitch when there is no layout selection (for exemple with `captures = (4)` in configuration).
When passing from take picture screen to camera preview, the take picture screen stay for ~1s with preview on screen. 
I'll try to make a picture of the glitch. 

Thanks.

**Comment by anxuae** [comment]
Hi bderenzo,

Do you use the Pi camera or an external camera?
I pushed a small fix that may correct that, but can not test for the moment. 
Please have a try on the master branch (follow the steps to [run a developing version](https://github.com/werdeil/pibooth#run-a-developing-version) )

Thanks
