### ISSUE TITLE
Add GPIO pin in config

### ISSUE THREAD

**Issue by werdeil** [werdeil/pibooth#38]
I think it would be interesting to add the GPIO pin in the config, se the user can easily change it if he already use one pin for another application. What do you think @anxuae ?

**Comment by Aurel-Charles** [comment]
that would be excellent !!

**Comment by anxuae** [comment]
Yes, it easily achievable

**Comment by anxuae** [comment]
Please have a try (https://github.com/werdeil/pibooth/commit/72d25e9074d30fe278503e79caa6183540811a9f)
I have not any more the means to test
