### ISSUE TITLE
Touch screen not working only on home / full screen

### ISSUE THREAD

**Issue by m91192** [werdeil/pibooth#44]
Hi project works like a charm thanks. I just cannot get how to set Start screen 'take photo' to be touched. In any size, mouse / touch / gpio does the job, but not in fullscreen.
Yet once this screen is passed, in full screen, all other screens work fine with touch...
help :)

**Comment by jasharrar** [comment]
Hi I used these commit changes:
https://github.com/werdeil/pibooth/commit/b462ba9a41d58f03fa55f26443bb6a820e3e1492

**Comment by anxuae** [comment]
Hello,

I fixed it in the commit that Jasharrar gives in it's comment. But it is not yet integrated in an official release.

@werdeil, maybe a new release can be done when the #43 is fixed?

anxuae

**Comment by werdeil** [comment]
#43 is now fixed, feel free to do a new release ;-)

**Comment by anxuae** [comment]
Fixed in ``pibooth`` 1.0.3
