### ISSUE TITLE
Hide arrows when a touchscreen is used

### ISSUE THREAD

**Issue by anxuae** [werdeil/pibooth#49]
It could be interesting to hide the arrows (indicating the HW buttons) when a touchscreen is used as they are useless.

**Comment by jasharrar** [comment]
I managed to do this by just editing the images in paint.  It would be good to have options so that you could choose this as an option on install.

**Comment by anxuae** [comment]
Can't find an easy way to detect if an touchscreen is used.
We can add a new key in the config, but this is one more...

An other way is the set empty value to `picture_btn_pin` or `print_btn_pin`.

Don't know what is the best option

**Comment by anxuae** [comment]
finally I added a new key in the config 
https://github.com/werdeil/pibooth/commit/17548529a1b6a6c6536749aaa33d6569971a469b
