### ISSUE TITLE
Set the border around images

### ISSUE THREAD

**Issue by layer91** [werdeil/pibooth#55]
Is there any way to reduce the border/padding that ends up in the print? Both left, right and bottom, to basically fill the paper as best possible. 
Footer test is set to nothing. 
Is there anything that can be done about this, or have i simply missed something?
It seems no matter the config I cannot do anything about the padding 

See attached image. Orientation is set to auto in both cases. 
 
These are 2 square images. 2848, 2848. I think this would be better in landscape
![2019-02-15-23-09-03_ptb](https://user-images.githubusercontent.com/47660266/52889312-40d3c380-3177-11e9-83ce-ceb70a139544.jpg)

This is two images with resolution 4288x2848 This would be better in portrait mode I think
![2019-02-15-23-16-02_ptb](https://user-images.githubusercontent.com/47660266/52889448-e2f3ab80-3177-11e9-8182-85119c452c61.jpg)

**Comment by werdeil** [comment]
Normally if you put no footer text it shall use the whole height of the photo to put the images. Can you confirm that you kept the "footer_text1" and "footer_text2" keys in the config but put empty value in it (like "" or None)?

I don't think it is a good idea to give the possibility to set the border size around images.

**Comment by layer91** [comment]
A more dynamic way to set up to layout would be amazing, but probably out of scope. 
The variables are set as
footer_test1 = 
footer_test2 = 
Should it rather be a double quote "" or the word None?

**Comment by anxuae** [comment]
Hi,

I'have pushed a fix in order to improve the `orientation=auto` mode, but this doesn't change the padding .

The `footer_test1` and `footer_test2` shall be empty (not None nor "").

anxuae

**Comment by layer91** [comment]
I'm glad to hear! We're already live now so, it is what it is. Works great with picam as preview tho! Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [werdeil/pibooth] Set the border around images (#55)From: Tony Anxuae To: werdeil/pibooth CC: layer91 ,Author Hi,
I'have pushed a fix in order to improve the orientation=auto mode, but this doesn't change the padding .
The footer_test1 and footer_test2 shall be empty (not None nor "").
anxuae

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/werdeil/pibooth","title":"werdeil/pibooth","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/werdeil/pibooth"}},"updates":{"snippets":[{"icon":"PERSON","message":"@anxuae in #55: Hi,\r\n\r\nI'have pushed a fix in order to improve the `orientation=auto` mode, but this doesn't change the padding .\r\n\r\nThe `footer_test1` and `footer_test2` shall be empty (not None nor \"\").\r\n\r\nanxuae\r\n"}],"action":{"name":"View Issue","url":"https://github.com/werdeil/pibooth/issues/55#issuecomment-464361451"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/werdeil/pibooth/issues/55#issuecomment-464361451",
"url": "https://github.com/werdeil/pibooth/issues/55#issuecomment-464361451",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by anxuae** [comment]
Ok, it seems difficult to add borders handling in config
