### ISSUE TITLE
Problem with new update and both button 1 and 2

### ISSUE THREAD

**Issue by Alex74300** [werdeil/pibooth#58]
Hi

I updated yesterday the Pibooth app and I now have a problem with buttons 1 and 2 when printing. I think the new function "Choosing the layout with the buttons 1 and 2" create a conflict with the print function. Both buttons 1 and 2 send a photo to print, whereas before only button 2 allowed printing. Button 1 reset the program and returned to the layout screen.
How can you change the problem so that each button has a specific function?
Thank you for your help!
alex

**Comment by Alex74300** [comment]
It's ok ! I unistall and update agin and it work !
thanks !

**Comment by anxuae** [comment]
Hi Alex,

Can you publish your `pibooth` config?

BR
anxuae

**Comment by anxuae** [comment]
Hi,
Some news about this issue ?
Thanks

**Comment by anxuae** [comment]
Can not reproduce. Without logs, I will close this issue in some days.

Regards.

Anxuae
