### ISSUE TITLE
Print photos from smartphone

### ISSUE THREAD

**Issue by fmarzocca** [werdeil/pibooth#59]
Hi,

I am wondering if your nice project is also able to download photos from bluetooth-connected smartphone and print them.
Is it restricted to only print the selfie that it takes?

Thanks
Fabio

**Comment by anxuae** [comment]
Hi Fabio,
No this project is not foreseen to drive a smartphone. This feature require too big changes and strong knowleges in Bluetooth stack.
Anxuae
