### ISSUE TITLE
Feature- print count for canon selphy

### ISSUE THREAD

**Issue by jasharrar** [werdeil/pibooth#62]
Hi 
I'm using a canon selphy so need to change ink every 38 prints and paper every 19 prints. Is there some way to have a count so a message pops up to change the media?

Thanks

**Comment by werdeil** [comment]
Hi, I understand the need but until now there is no way for the pibooth to know the status of the printer at startup, so we cannot know how many prints are left.

Until now the whole printing part is using cups in order to avoid handling each brand of printer. I don't see a way to change it easily.

@anxuae ?

**Comment by jasharrar** [comment]
I thought that may be the case, bit could a separate counter be added in the config as a work around. This would need to be "reset" manually by exiting pibooth and loading the config.

**Comment by anxuae** [comment]
Can have a look to CUPS attributes: https://www.cups.org/doc/spec-ipp.html
It seems possible to get the ink level if the printer shall the info with the CUPS server.

Otherwise a counter can be implemented.

**Comment by anxuae** [comment]
Hi @jasharrar,

I will add a counter in the config file, it will be displayed each time a new picture is sent to the printer.

Do you think that if the counter is reached, all print actions shall be blocked until counter reset?

anxuae

**Comment by jasharrar** [comment]
That would be really helpful, alternatively some kind of GUI message to replace the paper/ink. I think a lot of us are using cannon selphys. With 19 prints per pack and 38 prints per ink roll.

**Comment by anxuae** [comment]
Hi @jasharrar,

Can you make a test for me?

Connect your printer to your raspberry pi, power-on rpi&printer.
Then in a python shell, execute these lines:
```
import cups

p=cups.Connection()
attributes = p.getPrinterAttributes('<name of your printer>')

for name in attributes:
    if 'marker' in name:
    print(name, attributes[name])

```

Then can you post the result?
I would like to see it is possible to get the remaining supply levels of the printer.

Thanks

**Comment by anxuae** [comment]
New key 'max_pages' in config to define the printer counter.
The counter can be reset by opening/closing the settings menu.

**Comment by mattdsteele** [comment]
@jasharrar I know it's been a while, but I'm curious how your experience with the Canon Selphy went?

I'm considering picking one up for my photo booth project, but want to make sure it prints OK, you didn't have to do anything weird to configure it on the Pi, etc.

Thanks! 🙌

**Comment by sandrokeil** [comment]
@mattdsteele I can confirm that printing works with Canon Selphy CP1300 and this awesome app. I use a Raspberry PI 4 with 4GB RAM and Raspberry Pi OS Lite. After some configuration I got all the things working.

**Comment by dominiquegrota** [comment]
Hi, I confirm that your app is excellent !!! and it works with cp1300 printer. 
The [PRINTER][max_pages] count is working. I looked up to find how to reset the counter if i open and close the setup menu, the counter is allways on 0. I have to reset all counters to get it work again, but all pictures are destroyed :-(

Can you give me a tip to rest only de printer coutner.

Thankyou
