### ISSUE TITLE
Footer Font

### ISSUE THREAD

**Issue by sbinder** [werdeil/pibooth#63]
How does the "Fonts url" line in the config file work? I assume it is used to set the footer font(s), but I haven't been able to figure out how to use it.

**Comment by anxuae** [comment]
In this key, you can put the path to a TTF file. Or you can use the default font files installed on your machine. For instance:
```
fonts = Arial.ttf, Verdana.ttf
```

**Comment by anxuae** [comment]
Does it answer to your request?
