### ISSUE TITLE
Offset Arrow Position

### ISSUE THREAD

**Issue by iditude** [werdeil/pibooth#68]
Hello,

Any way to create a config to offset the position of the arrow (left or right)? For physical reasons I couldn't place the button at the very spot.

Somehting like a pixel offset should work I think.

Thanks

**Comment by anxuae** [comment]
Hi @iditude,

This could be added on the configuration file, also may be the possibility to choose the bottom or top position for the arrows.

anxuae

**Comment by anxuae** [comment]
Ready for next release
