### ISSUE TITLE
Add print process

### ISSUE THREAD

**Issue by werdeil** [werdeil/pibooth#7]

**Comment by anxuae** [comment]
Used CUPS as described in https://www.howtogeek.com/169679/how-to-add-a-printer-to-your-raspberry-pi-or-other-linux-computer/

**Comment by anxuae** [comment]
Need to add a new dependency to `pycups` package

**Comment by anxuae** [comment]
Dont forget to install header files of CUPS, it's required by `pycups`

`sudo apt-get install libcups2-dev`

**Comment by anxuae** [comment]
https://github.com/werdeil/pibooth/commit/871f0908e81f109311da74f413fd1eb51c18e333
