### ISSUE TITLE
Different background depending on number of shot

### ISSUE THREAD

**Issue by themaluxis** [werdeil/pibooth#74]
Hi,
is it possible to define several backgrounds according to the number of photos we will take? 
For example, a background with my text in the bottom right if I took 3 pictures, but the background with the text centered in the middle if I only take one picture.

Thank you. Thank you.

**Comment by themaluxis** [comment]
@anxuae added the enhancement  label 2 days ago
so you plan to work on this ? :)

**Comment by anxuae** [comment]
Maybe yes, maybe not :-)

We can imagine something like that:

```ini

    [PICTURE]

    # Background RGB color or path to a background image applied on both pictures
    bg_color = (255, 255, 255)
```

This key can take two name/path/url:

```ini

    [PICTURE]

    # RGB color applied on picture 1 and background image applied on picture 2
    bg_color = ( (255, 255, 255), "path/to/my/background.png")
```

**Comment by anxuae** [comment]
@themaluxis does it fit your expectations if I implement this change?

**Comment by themaluxis** [comment]
Sure :)
