### ISSUE TITLE
Set option for one image instead of 4

### ISSUE THREAD

**Issue by werdeil** [werdeil/pibooth#8]

**Comment by werdeil** [comment]
I think that #15 shall be done before this one

**Comment by anxuae** [comment]
The option in config already exists:
```
[PICTURE]
# How many pictures to take (4 max)
captures = 4
```
I think that the only thing to change is the `concatenate ` function.

**Comment by werdeil** [comment]
This ticket is to add an option on the interface to change during the use (either a 1 shot or a 4 shot) not in the config

**Comment by anxuae** [comment]
A yes, I've lost my mind

**Comment by anxuae** [comment]
May be it can be done by using the "picture" button (and specific keyboard combo):
- long press
- several time press

**Comment by werdeil** [comment]
Or a middle screen of 5 seconds where the suer choose between the 2

**Comment by werdeil** [comment]
I have introduced the middle screen, if you want you can work on the action handling

**Comment by anxuae** [comment]
https://github.com/werdeil/pibooth/commit/395d3fcbe41a673a193094ba9c51fcdf1351d3fa
