### ISSUE TITLE
Disable Printer-Function

### ISSUE THREAD

**Issue by andhey** [werdeil/pibooth#85]
Is it possible to switch off the printing function for example via --config, although a printer is installed?
If I set the number of prints in --config to 0, at least one expression is still possible.

**Comment by anxuae** [comment]
Hi Andhey,

Sorry but I don't see the parameter that you have changed.
I you set `[PRINTER][max_pages ]` = 0, is it still possible to print?

If yes, this is a bug and I will fix it soon.

Thanks
anxuae

**Comment by andhey** [comment]
Yes, i mean `[PRINTER][max_pages] = 0,`and Yes I can still print by pressing the blinking push-Button for printing.

**Comment by andhey** [comment]
Sorry my fault. I habe hoben the wring Parameter. Everything is Fine now.
